# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A8sCli < Formula
  desc "The official CLI for Autonomous 8s"
  homepage "https://github.com/ITProfessional-Gen01/a8s-cli"
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.1/a8s-cli_darwin_amd64.tar.gz"
      sha256 "59ebef62bb4906af6d7dc9607ff6ced082427013370f2444e58aea6b460947d8"

      def install
        bin.install "a8s-cli"
      end
    end
    on_arm do
      url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.1/a8s-cli_darwin_arm64.tar.gz"
      sha256 "25b361c585894d475a1e0d583e4a689eec18e08c9a88b55205b79486d78ee98a"

      def install
        bin.install "a8s-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.1/a8s-cli_linux_amd64.tar.gz"
        sha256 "a15939034c584f4a4351ca0ab4050285007c498435b893c67e20c5c442d985f6"

        def install
          bin.install "a8s-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.1/a8s-cli_linux_arm64.tar.gz"
        sha256 "e2c6b9a722ab8932543cb58a03dd9f50f4548ddc5730c25e6a41ff703349ddb1"

        def install
          bin.install "a8s-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/a8s-cli --version"
  end
end
