# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class A8sCli < Formula
  desc "The official CLI for Autonomous 8s"
  homepage "https://github.com/ITProfessional-Gen01/a8s-cli"
  version "1.1.5"

  on_macos do
    on_intel do
      url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.5/a8s-cli_darwin_amd64.tar.gz"
      sha256 "bba4dc14e81a6df8af594b36ec5f6f63582984966aa13735820fed9e605984cc"

      def install
        bin.install "a8s-cli"
      end
    end
    on_arm do
      url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.5/a8s-cli_darwin_arm64.tar.gz"
      sha256 "46e6e1cc4275d3ee327b47f05c4a3e6f8a96e96003115d53382fbc182de20a7d"

      def install
        bin.install "a8s-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.5/a8s-cli_linux_amd64.tar.gz"
        sha256 "4d36d77abb7090d31260e1eb3ce9f9ea397c7c443b08b6fa30793fe76939cd2c"

        def install
          bin.install "a8s-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ITProfessional-Gen01/a8s-cli/releases/download/v1.1.5/a8s-cli_linux_arm64.tar.gz"
        sha256 "aa055a559ca104fec3a909fe7449c77850e77e7761185d64ca7772ed1aab4fb6"

        def install
          bin.install "a8s-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/a8s-cli --version"
  end
end
