version: 1
project_name: a8s-cli

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    # owner and name will be automatically detected from the remote

brews:
  - repository:
      # owner and name will be automatically detected from the remote
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: HomebrewFormula
    homepage: "https://github.com/PorKeat/a8s-tui"
    description: "The official CLI for Autonomous 8s"
    test: |
      system "#{bin}/a8s-cli --version"
